### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript-analyzer#6]
Currently there is no `CONTRIBUTING.md` present in the root of this repository. Add a `CONTRIBUTING.md` with at least the following:

## How to general

- how to contribute
- what is expected in issues
- what is expected in pull requests
- what steps to take in order to submit a PR 

## How to specific

- add a new analyzer (for an exercise)
- update an analyzer (sync)
- add new behaviour to an existing analyzer
- change the copy that is generated

Have a look at [`problem-specifications/CONTRIBUTING.md`](https://github.com/exercism/problem-specifications/blob/master/CONTRIBUTING.md).

**Comment by SleeplessByte** [comment]
Fixed by #5

**Comment by zeckdude** [comment]
I could help with this, but I don't know the answers to some of these areas. Can you help me fill in the blanks and I'll write it up?

**How to general**

- how to contribute: I'm assuming it's as easy as reaching out on the slack group and then just looking at the issues, claiming an issue and then forking the repo and once the work is done, create a PR? Am I missing something? Btw, do we want to create a `javascript-analyzer` slack group? 
- what is expected in issues: I don't know the answer to this. Need clarification.
- what is expected in pull requests:  I don't know the answer to this. Need clarification.
- what steps to take in order to submit a PR: I'm assuming it's just forking the repo and once the work is done, create a PR? I would ofcourse write out the exact steps, but that's the basic idea, right?

**How to specific**

- add a new analyzer (for an exercise): Can we add new analyzer's even if there is no issue for it? I assume this just involves dissecting one of the existing analyzers and then writing the logic to fit for the exercise you want to auto mentor? 
- update an analyzer (sync): What do you mean by sync? I don't know the answer to this. Need clarification.
- add new behaviour to an existing analyzer: I don't know the answer to this. Need clarification.
- change the copy that is generated: Is there is a standard operating procedure for this? I would assume it would be tp just create a PR for fix the copy. Am I missing something?

**Comment by SleeplessByte** [comment]
@zeckdude have a look at https://github.com/exercism/javascript-analyzer/commit/c34f480ffa6b0e81e23abeba5fd5c1a4c3fd8e4c which is the first iteration of the document. This should answer most of your questions.
